### ISSUE TITLE
Sourcehut doesn't support HTTPS access when adding ".git" at the end

### ISSUE THREAD

**Issue by danyspin97** [nvim-neorocks/rocks-git.nvim#21]
The plugin [lsp_lines.nvim](https://git.sr.ht/~whynothugo/lsp_lines.nvim) is either accessible via:
- https://git.sr.ht/~whynothugo/lsp_lines.nvim
- `git@git.sr.ht:~whynothugo/lsp_lines.nvim`

However, sourcehut doesn't allow https://git.sr.ht/~whynothugo/lsp_lines.nvim.git, making `rocks-git.nvim` to fail.

I think that checking `.git` is good to prevent git running on random websites, but at the same time it requires a new requisite (adding `.git` at the end of an HTTPS repository) which many users are not used to and also create this issue.

**Comment by mrcjkb** [comment]
Hey :wave:

thanks for reporting.
I guess I could lift the constraint of URLs having to end with `.git` and then use `git ls-remote <url>` to check if it's a URL that can be fetched with git.

**Comment by mrcjkb** [comment]
Actually, using `git ls-remote` would be terrible for performance, especially since it can't be used somewhere where it's called asynchronously.
For now, I'm going to hard code sourcehut support.

**Comment by danyspin97** [comment]
Thank you for the fast fix 😄
