### ISSUE TITLE
Branch is sometimes not respected

### ISSUE THREAD

**Issue by treeman** [nvim-neorocks/rocks-git.nvim#31]
I've ran into the issue that sometimes the `branch` isn't respected.

I haven't gotten a minimal repeat but I suspect `Rocks update` may play a part.

For example I had this:

```toml
"trouble.nvim" = { git = "folke/trouble.nvim", branch = "dev" }
```

Then ran `Rocks update` and the repo at `~/.local/share/nvim/site/pack/rocks/start/trouble.nvim` changed to `main` (at least I think that was the root cause).

I tried `Rocks prune`, then added back the `trouble.nvim` line to `rocks.toml` and ran `Rocks sync`, yet the branch was still at `main`. I had to go into the package and manually switch the branch to make it work.

**Comment by mrcjkb** [comment]
Is your rocks-git.nvim install up to date? 
This should have been fixed: 

- https://github.com/nvim-neorocks/rocks-git.nvim/pull/29

**Comment by treeman** [comment]
Oh, sorry! I had it pinned to the `1.5.1` version. I'll use `scm` for now.

Thanks!

**Comment by mrcjkb** [comment]
> Then ran Rocks update and the repo at ~/.local/share/nvim/site/pack/rocks/start/trouble.nvim changed to main (at least I think that was the root cause).

- On `Rocks update`, rocks-git runs `git pull` if there's no `rev` (used to pin to a tag or revision).
- On `Rocks sync`, if there's no `rev`, but there is a `branch`, it checks out the branch and then runs `git pull`.

**Comment by treeman** [comment]
Funny, I think `Rocks update` updated `rocks-git` from `1.5.0` to `1.5.1` at the same time, so I was running `1.5.0` when the error happened.
