### ISSUE TITLE
Prune command doesn't seem to work for rocks-git.nvim packages

### ISSUE THREAD

**Issue by simifalaye** [nvim-neorocks/rocks-git.nvim#34]
Versions:
- rocks.nvim = "2.31.3"
- rocks-git.nvim = "1.5.1"

I can successfully run the "update", "edit", "sync", and "install" commands for git packages but running the "prune" command (`:Rocks prune tummetott/unimpaired.nvim`) yields this error:
```
[START][2024-06-20 20:12:21] rocks.nvim logging initiated
ERROR | 2024-06-20 20:12:26 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:64 | luarocks CLI FAILED
ERROR | 2024-06-20 20:12:26 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:65 | 
Error: cannot find package tummetott/unimpaired.nvim
Use 'list' to find installed rocks.

ERROR | 2024-06-20 20:12:26 | ...er/.local/share/nvim/rocks/rocks_rtp/lua/rocks/state.lua:106 | Could not get dependencies for rock tummetott/unimpaired.nvim: 
Error: cannot find package tummetott/unimpaired.nvim
Use 'list' to find installed rocks.

ERROR | 2024-06-20 20:12:26 | ...er/.local/share/nvim/rocks/rocks_rtp/lua/rocks/state.lua:115 | ...er/.local/share/nvim/rocks/share/lua/5.1/nio/control.lua:145: Could not get dependencies for rock tummetott/unimpaired.nvim: 
Error: cannot find package tummetott/unimpaired.nvim
Use 'list' to find installed rocks.

ERROR | 2024-06-20 20:12:26 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:64 | luarocks CLI FAILED
ERROR | 2024-06-20 20:12:26 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:65 | 
Error: Could not find rock 'tummetott/unimpaired.nvim' in /home/user/.local/share/nvim/rocks

ERROR | 2024-06-20 20:12:30 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/init.lua:682 | Prune completed with errors! Run ':Rocks log' for details.
```

It seems it's trying to prune it as a luarocks package and not as a rocks-git package.

*NOTE*: I put some output logs on the rocks-git "prune" callback handler (rocks_git.get_prune_callback) and it seems that the prune callback isn't being called whereas the other handlers are being called when you run the "Rocks <cmd>" action.

*NOTE*: If you run the prune command just using the repo name (no owner, ex. "unimpaired.nvim"), it removes the plugin spec from the rocks.toml file (I assume this is a final prune handler) but the repo still exists in the rocks-git rtp. You can then just run `:Rocks sync` after and that works but the prune command should work on its own with the `owner/repo` name.

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for the detailed report 🙏

**Comment by mrcjkb** [comment]
> If you run the prune command just using the repo name (no owner, ex. "unimpaired.nvim")

This is the intended interface. The tab completions should show you which packages can be pruned.

**Comment by simifalaye** [comment]
> This is the intended interface

I was rather pointing that there is a workaround for now to get pruning of rocks-git packages to work (without just manually removing the repo directory from the nvim data path). Though this works (prune just the repo name which removes it from the config and then sync), I think that you should be able to prune the entire rocks-git package in one command.

**Comment by mrcjkb** [comment]
> I think that you should be able to prune the entire rocks-git package in one command.

That's what https://github.com/nvim-neorocks/rocks.nvim/pull/400 will fix :smile: 

What I was referring to by "this is the intended interface" is the fact that you have to pass in the rock name to prune, not the git URL.

**Comment by simifalaye** [comment]
@mrcjkb Are you sure this is fixed? Just updated rocks.nvim version to 2.32.0 and when I run the `prune owner/repo` command, I get a notification saying that the prune completed BUT the git repo still exists in `<stddatapath>/site/pack/rocks/start/repo` and in my rocks.toml

**Comment by mrcjkb** [comment]
Yep. `Rocks prune` doesn't take an `owner/repo` argument. [You have to pass in the rock name](https://github.com/nvim-neorocks/rocks.nvim?tab=readme-ov-file#uninstalling-rocks).

But I've just realised the command completions don't work for rocks that are managed by external modules (like rocks-git and rocks-dev).

**Comment by mrcjkb** [comment]
https://github.com/nvim-neorocks/rocks.nvim/issues/419

**Comment by simifalaye** [comment]
Few notes:
- The rocks-git README.md says all the sub-commands take the plugin short name "owner/repo" so this is what I would expect to use when removing a rocks-git package. I think for consistency, it would be better to have it work this way because it is clear when you are installing or pruning a rocks-git repo vs a luarocks package but if there are technical limitations, then I think the readme should clarify that the "owner/repo" short name does not apply to the prune command.
- I did already try just the repo name and it didn't work to remove the git repo from the runtimepath UNTIL I ran it a second time. In my testing (maybe I have something setup incorrectly), I need to run `:Rocks prune` twice for the rocks-git package to actually get pruned.

**Comment by mrcjkb** [comment]
> The rocks-git README.md says all the sub-commands take the plugin short name "owner/repo" so this is what I would expect to use when removing a rocks-git package.

This is what the rocks-git readme says:

> You can use the same `:Rocks {install|update|sync|prune}` commands as you would use to install rocks with rocks.nvim.
>
> The only difference is the `:Rocks install {plugin} {args?}` command.

> I did already try just the repo name and it didn't work to remove the git repo from the runtimepath UNTIL I ran it a second time.

rocks-git doesn't remove plugins from the rtp after pruning. It just deletes the repo from the file path so that it doesn't get added to the runtimepath on the next start.

**Comment by simifalaye** [comment]
> This is what the rocks-git readme says:

But the next part you left out is the part I'm referring to which states that the 'plugin' argument is the repo short name, ie. "owner/repo"

**Comment by mrcjkb** [comment]
> Could you also comment on the prune needing to be run twice?

I did:

>> rocks-git doesn't remove plugins from the rtp after pruning. It just deletes the repo from the file path so that it doesn't get added to the runtimepath on the next start.

If it needs to be run twice in order to delete the repo, then something must be wrong. Do you have the same behaviour with `sync`?

**Comment by simifalaye** [comment]
> I did:

My bad for not wording it properly. I meant the file path where the plugin was downloaded and then added to the runtime (ie. <datapath>/site/pack/rocks/**/*) 

> If it needs to be run twice in order to delete the repo, then something must be wrong. Do you have the same behaviour with `sync`?

Sync works immediately, I've only seen it on prune. I'll keep testing a few things just to make sure it's not on my end but so far, it always take two prunes for rocks-git packages when I load up nvim.

**Comment by mrcjkb** [comment]
> Sync works immediately, I've only seen it on prune. 

That's very strange. `prune` and prune on `sync` use exactly the same function.
I'll have to investigate that on Friday.
