### ISSUE TITLE
Rocks update result in ENONET error after removing rocks-git plugin

### ISSUE THREAD

**Issue by austinliuigi** [nvim-neorocks/rocks-git.nvim#37]
When I run `:Rocks update`, I get the following error:

![image](https://github.com/nvim-neorocks/rocks.nvim/assets/85013922/5863f589-08d7-4665-b26b-4dc45c3fefaa)

It worked when I ran it earlier today, but after attempting to lazy-load my plugins with `rocks-lazy.nvim` I noticed that converting my `rocks-git` plugins to use `opt = true` wasn't working; they were staying in `~/.local/share/nvim/site/pack/rocks/start`. When I tried uninstalling the plugin and reinstalling, it wouldn't install. I tried reinstalling `rocks.nvim` by deleting `~/.local/share/nvim/rocks/` and `~/.local/share/nvim/site/pack/` and re-triggering the bootstrap. However, after reinstallation, I still get the error shown in the image when I run `:Rocks update`.

Update: I figured that this only occurs after removing a `rocks-git` plugin. So after doing a fresh install of `rocks.nvim`, this is the sequence I followed:
```
- run :Rocks sync
- run :Rocks update <= works
- comment out a rocks-git plugin from rocks.toml
- run :Rocks sync
- run Rocks update <= errors
```

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for reporting. I'll try to reproduce later today.

**Comment by mrcjkb** [comment]
Also, This looks suspicious in your config 

```lua
local rocks_config = {
    rocks_path = vim.fs.normalize(install_location),
    luarocks_binary = vim.fs.joinpath(install_location, "bin", "luarocks"),
  }
```

Can you please try unsetting `luarocks_binary`?

**Comment by austinliuigi** [comment]
Another issue that may be related and could possibly provide more context : after following these steps after reinstallation that I mentioned above,

```
- run :Rocks sync
- run :Rocks update <= works
- comment out a rocks-git plugin from rocks.toml
- run :Rocks sync
- run Rocks update <= errors
```

I also cannot re-install the plugin that I commented out. When I uncomment it and run `:Rocks sync`, it doesn't install. Note that the sync doesn't show any signs of failing, it just processes for a little while with no progress messages then shows "Completed" when done. It is only when I run `:Rocks update` that I get the ENONET error.

**Comment by mrcjkb** [comment]
I haven't been able to reproduce the behaviour you're describing.
But I've also noticed your `rocks.nvim` installation and its modules (rocks-git, etc.) are quite out of date.

Could you please update to the latest versions and then see if the issue still persists?

**Comment by mrcjkb** [comment]
If you push your updated config to another branch and link it for me, I can try and reproduce again :smile:

**Comment by austinliuigi** [comment]
So I was probing the source code of rocks.nvim and rocks-git.nvim to see if I could get more information and I found out why rocks-git wasn't installing plugins. I fixed the issue in [this PR](https://github.com/nvim-neorocks/rocks.nvim/pull/469). Interestingly, I currently can't reproduce the ENONET error when I `:Rocks update`, even when I revert the fix for rocks-git not installing plugins. Maybe it's some kind of race condition?

I also mentioned in the PR that rocks-git seems to install plugins fine on the first run of `:Rocks sync` after a fresh install of rocks.nvim. I'm curious to know f you have any ideas why.

**Comment by mrcjkb** [comment]
Thanks for digging and for the fix :pray:

> I also mentioned in the PR that rocks-git seems to install plugins fine on the first run of :Rocks sync after a fresh install of rocks.nvim. I'm curious to know f you have any ideas why.

I think it could be if rocks-git isn't installed yet. To make sure sync works when you first run it (before extensions like rocks-git are installed), rocks.nvim collects all the rocks it couldn't handle itself, loads external handlers after installing them, and [then retries to install the rocks it couldn't install previously](https://github.com/nvim-neorocks/rocks.nvim/blob/735f4a036b0008586b299c1fcd16a1014e3c8c83/lua/rocks/operations/sync.lua#L142).

**Comment by austinliuigi** [comment]
I see, thanks for the explanation. Since I can't reproduce the ENONET error, this issue could probably be closed but I'll leave that up to you. Thanks for all the help and the great package manager :)
