### ISSUE TITLE
`fatal: protocol is not supported` with custom git config

### ISSUE THREAD

**Issue by rupansh** [nvim-neorocks/rocks-git.nvim#46]
I am trying to add the following git dependency:

```toml
"catpuccin.nvim" = { git = "https://github.com/catppuccin/nvim" }
```

here's my custom git config

```
[url "git@github-rupansh:"]
    insteadOf = https://github.com/
[url "git@github-rupansh:"]
    insteadOf = ssh://git@github.com/
```

`Rocks sync` fails with the following error:
`fatal: protocol 'git@github-rupansh:https' is not supported`

Meanwhile, `git clone https://github.com/catppuccin/nvim` works fine

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for reporting.
I'm about to push a fix.

The reason you're running into this is because rocks-git.nvim currently expects a shorthand (e.g. `owner/repo` or `github:owner/repo`) or a URL that ends in `.git`.
It should be fine to remove the latter restriction.
