### ISSUE TITLE
install: pin current revision if none is found

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks-git.nvim#53]
On install, if there's no tag, we pin the latest semver tag from remote:

https://github.com/nvim-neorocks/rocks-git.nvim/blob/c8fe6ae4011bea1a00c6b0852ddee1db15d1f11a/lua/rocks-git/init.lua#L134-L139

We should also pin the latest revision if no tag is found.

**Comment by teto** [comment]
when you hit this coupled with https://github.com/nvim-neorocks/rocks-git.nvim/issues/54 you end up with non-installed packages so I support both tickets \o/
