### ISSUE TITLE
How can I update packages installed with rocks-git?

### ISSUE THREAD

**Issue by flexagoon** [nvim-neorocks/rocks-git.nvim#62]
Since rocks-git automatically pins the latest revision, packages installed with it are not updated when you run `:Rocks update`. Is there a way to update all rocks-git packages to the latest commit?

**Comment by mrcjkb** [comment]
That sounds like a regression that was introduced when we started pinning packages. I'll look into it.

**Comment by mrcjkb** [comment]
lol I found the issue

```lua
:lua =vim.version.parse("d818fd0624205b34e14888358037fb6f5dc51234")
{
  major = 818,
  minor = 0,
  patch = 0,
  <metatable> = {
    __eq = <function 1>,
    __index = <function 2>,
    __le = <function 3>,
    __lt = <function 4>,
    __newindex = <function 5>,
    __tostring = <function 6>
  }
}
```
