### ISSUE TITLE
[Feature] Async installation

### ISSUE THREAD

**Issue by xsh005** [nvim-neorocks/rocks-git.nvim#8]
Right now rocks.nvim would block on `Rocks sync` (but only while syncing rocks.nvim itself), it would block the ui. It would be nice if it's not the case.

**Comment by mrcjkb** [comment]
I've made rocks-git async, but after a test, I believe there's still some UI blocking.
So I've opened https://github.com/nvim-neorocks/rocks.nvim/issues/109

@xsh005 could you please update rocks-git and see if the situation has improved for you?
